"""Initial models

Revision ID: b41a0816fcda
Revises: 
Create Date: 2020-04-14 07:29:41.924866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41a0816fcda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('prop', sa.UnicodeText(), nullable=False),
    sa.Column('raw_duration', sa.UnicodeText(), nullable=True),
    sa.Column('start', sa.UnicodeText(), nullable=False),
    sa.Column('end', sa.UnicodeText(), nullable=True),
    sa.Column('done', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effect_name'), 'effect', ['name'], unique=False)
    op.create_table('effect_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effect_group_name'), 'effect_group', ['name'], unique=False)
    op.create_table('effect_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effect_stack_name'), 'effect_stack', ['name'], unique=False)
    op.create_table('effect_group_to_effect_stack',
    sa.Column('effect_group_id', sa.Integer(), nullable=False),
    sa.Column('effect_stack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['effect_group_id'], ['effect_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['effect_stack_id'], ['effect_stack.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('effect_group_id', 'effect_stack_id')
    )
    op.create_table('effect_to_effect_group',
    sa.Column('effect_id', sa.Integer(), nullable=False),
    sa.Column('effect_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['effect_group_id'], ['effect_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['effect_id'], ['effect.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('effect_id', 'effect_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('effect_to_effect_group')
    op.drop_table('effect_group_to_effect_stack')
    op.drop_index(op.f('ix_effect_stack_name'), table_name='effect_stack')
    op.drop_table('effect_stack')
    op.drop_index(op.f('ix_effect_group_name'), table_name='effect_group')
    op.drop_table('effect_group')
    op.drop_index(op.f('ix_effect_name'), table_name='effect')
    op.drop_table('effect')
    # ### end Alembic commands ###
