"""Lights

Revision ID: 81f712a16149
Revises: 05ae88c17916
Create Date: 2020-04-24 18:05:31.631637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f712a16149'
down_revision = '05ae88c17916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('x_pos', sa.Integer(), nullable=False),
    sa.Column('y_pos', sa.Integer(), nullable=False),
    sa.Column('color', sa.Unicode(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_light_name'), 'light', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('light')
    # ### end Alembic commands ###
